# Generated by Django 2.2.1 on 2019-06-30 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reg_data',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
