# Generated by Django 2.2.1 on 2019-06-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_member_reg_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
